### PR TITLE
Add imageHashMH, which is a more precise hashing function

### PR DESCRIPTION
**Pull request by AVVS**
It returns 72 byte hex buffer, which is used as a hash.
More info on that function available on [phash.org](http://www.phash.org/docs/design.html)

### CODE REVIEW

**Comment by jonathanong** [comment]
awesome! didn't know about this.

can you add a test and docs? be sure to squash at the end and i'll merge ASAP!

**Comment by jonathanong** [comment]
specifically, i'd like to keep my 100% coverage :)

**Comment by AVVS** [comment]
In the upcoming week or so. Need to finish other stuff based on this first, tight deadlines :P

**Comment by lovell** [comment]
Thanks Vitaly. When you rebase/squash from master you'll pick up https://github.com/mgmtio/phash-image/commit/42240ac36dd4b9b7546b73ed88d7aba5411c9797 which should fix the CI failure too.

**Comment by jonathanong** [comment]
thanks! i released this as 3.2.0. added some simple and updated docs!

some tests to actually check that the results are sane by actually using the hamming distance would be great, but not a big deal.

**Pull request closed without merging**
