### PR TITLE
Create buffer C++ side

### LINKED ISSUE #1: Create the node buffer in c++ land
- [ ] return `New::Buffer()` via `nan`
- [ ] API should only return `Buffer()` instances - users would be required to `.toString()` themselves

### LINKED ISSUE #10: ulong64 returned hash is not always the same bytes long
pHashImage = require('phash-image');

    pHashImage(imagePath, true).then(function(hash) {
        console.log('hash length:', hash.length);
        hash = _.padRight(hash, 20, '0'); // <== I wouldn't expect to have to do this !
      });

Sometimes returned hash length is 20, sometimes it is 19!!!

### PR DESCRIPTION
**Pull request by PlasmaPower**
Resolves #1 and resolves #10

### CODE REVIEW

**Comment by PlasmaPower** [comment]
First time working with C++ in Node! :tada:

**Comment by PlasmaPower** [comment]
I removed {u,}int_to_hex because they aren't used any more. Side note: is it possible that the ulong64 byte order is correct, and it was just being incorrectly outputted before? Fixing that would be a breaking change of course.

**Comment by jonathanong** [comment]
adding you as a collab :) not really using htis right now

**Comment by PlasmaPower** [comment]
@jonathanong Thanks! To be honest, the reason I made this PR was just to get the $15 bounty on #1, but I should be able to maintain this :).

**Comment by jonathanong** [comment]
oh thank god because i don't know how to refund that money

**Comment by PlasmaPower** [comment]
@jonathanong Yeah, a lot of bounties on bountysource seem to fall apart that way :P

**Comment by PlasmaPower** [comment]
@jonathanong Mind accepting the claim on bountysource? It will auto accept in 2 weeks, but this will be a bit easier. Link to issue on bountysource: https://www.bountysource.com/issues/5524486-create-the-node-buffer-in-c-land

**Comment by PlasmaPower** [comment]
@jonathanong Thanks!

**Comment by jonathanong** [comment]
:D

**Pull request merged**
